import fs from "fs-extra";
import path from "node:path";
import { intro, outro, spinner, log } from "@clack/prompts";
import { loadConfig, ALL_CLIENTS, type AiClient } from "../config.js";

interface DiscoveredSkill {
  name: string;
  dir: string;
  markdown: string;
}

export interface CompileOptions {
  targets?: AiClient[];
}

export async function runCompile(
  targetDir: string,
  opts: CompileOptions = {},
): Promise<void> {
  intro("agentic-sync compile");
  const s = spinner();

  const root = path.resolve(targetDir);
  const skillsDir = path.join(root, ".agents", "skills");

  s.start("Loading synthesized skills...");
  if (!(await fs.pathExists(skillsDir))) {
    s.stop("No skills found.");
    log.warn(
      "No .agents/skills/ directory. Run `agentic-sync add <skill>` first.",
    );
    outro("Nothing to compile.");
    return;
  }

  const skills = await loadSkills(skillsDir);
  s.stop(`Loaded ${skills.length} skill(s).`);

  if (skills.length === 0) {
    log.warn("Skills directory is empty.");
    outro("Nothing to compile.");
    return;
  }

  const cfg = await loadConfig(root);
  const targets: AiClient[] =
    opts.targets && opts.targets.length > 0
      ? opts.targets
      : cfg?.targets && cfg.targets.length > 0
        ? cfg.targets
        : [...ALL_CLIENTS];

  log.info(`Targets: ${targets.join(", ")}`);

  if (targets.includes("claude")) {
    s.start("Writing CLAUDE.md...");
    await writeClaudeMd(root, skills);
    s.stop("Wrote CLAUDE.md");
  }

  if (targets.includes("copilot")) {
    s.start("Writing .github/copilot-instructions.md...");
    await writeCopilotInstructions(root, skills);
    s.stop("Wrote .github/copilot-instructions.md");
  }

  if (targets.includes("cursor")) {
    s.start("Writing .cursor/rules/*.mdc ...");
    await writeCursorRules(root, skills);
    s.stop(`Wrote ${skills.length} .cursor/rules/*.mdc file(s)`);
  }

  outro("Compile complete.");
}

async function loadSkills(skillsDir: string): Promise<DiscoveredSkill[]> {
  const entries = await fs.readdir(skillsDir, { withFileTypes: true });
  const out: DiscoveredSkill[] = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const dir = path.join(skillsDir, e.name);
    const skillMd = path.join(dir, "SKILL.md");
    if (!(await fs.pathExists(skillMd))) continue;
    out.push({
      name: e.name,
      dir,
      markdown: await fs.readFile(skillMd, "utf8"),
    });
  }
  return out;
}

const BEGIN_MARKER = "<!-- AGENTIC-SYNC:BEGIN -->";
const END_MARKER = "<!-- AGENTIC-SYNC:END -->";

function block(skills: DiscoveredSkill[]): string {
  const sections = skills.map(
    (s) => `\n### Skill: ${s.name}\n\n${stripFrontmatter(s.markdown).trim()}\n`,
  );
  return `${BEGIN_MARKER}\n# Project-specific AI guidance (generated by agentic-sync)\n\nThe sections below were synthesized from this repository's code. Do not edit by hand — re-run \`agentic-sync compile\` to refresh.\n${sections.join("\n---\n")}\n${END_MARKER}`;
}

function stripFrontmatter(md: string): string {
  if (!md.startsWith("---")) return md;
  const end = md.indexOf("\n---", 3);
  if (end === -1) return md;
  return md.slice(end + 4).replace(/^\s*\n/, "");
}

async function upsertManaged(file: string, content: string): Promise<void> {
  await fs.ensureDir(path.dirname(file));
  let existing = "";
  if (await fs.pathExists(file)) existing = await fs.readFile(file, "utf8");

  const beginIdx = existing.indexOf(BEGIN_MARKER);
  const endIdx = existing.indexOf(END_MARKER);

  if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
    const before = existing.slice(0, beginIdx).replace(/\s+$/, "");
    const after = existing
      .slice(endIdx + END_MARKER.length)
      .replace(/^\s+/, "");
    const next =
      [before, content, after].filter(Boolean).join("\n\n").trim() + "\n";
    await fs.writeFile(file, next, "utf8");
    return;
  }

  const next =
    (existing.trim() ? existing.trim() + "\n\n" : "") + content + "\n";
  await fs.writeFile(file, next, "utf8");
}

async function writeClaudeMd(
  root: string,
  skills: DiscoveredSkill[],
): Promise<void> {
  await upsertManaged(path.join(root, "CLAUDE.md"), block(skills));
}

async function writeCopilotInstructions(
  root: string,
  skills: DiscoveredSkill[],
): Promise<void> {
  await upsertManaged(
    path.join(root, ".github", "copilot-instructions.md"),
    block(skills),
  );
}

async function writeCursorRules(
  root: string,
  skills: DiscoveredSkill[],
): Promise<void> {
  const dir = path.join(root, ".cursor", "rules");
  await fs.ensureDir(dir);
  for (const skill of skills) {
    const file = path.join(dir, `${skill.name}.mdc`);
    const header = [
      "---",
      `description: ${skill.name} — generated by agentic-sync`,
      'globs: ["**/*"]',
      "alwaysApply: false",
      "---",
      "",
    ].join("\n");
    await fs.writeFile(
      file,
      header + stripFrontmatter(skill.markdown).trim() + "\n",
      "utf8",
    );
  }
}
